PR#6: Styled components prep
Vik0411/lotr pull request #14
Opened 2023-09-23 07:30 UTC by Vik0411

<img width="1090" alt="Screenshot 2023-09-23 at 8 38 31 AM" src="https://github.com/Vik0411/lotr/assets/50553439/704a78bf-87c8-427f-bc28-d8558e8a9746">

Current state in pic aboce. I would like the input to be made also more rounded if possible. Also, make the elements centered in better way, as well, as the "overreach" on the first button above. Also, quite a few styles are not used in the end here, so perhaps we will need to clean then.

2023-09-23 07:34 UTC, Vik0411 commented on src/context.tsx
> +    allHeroes: [
this might better b moved to the other open PR now. it is better fit imo

2023-10-06 19:06 UTC, komret requested changes
> I would like the input to be made also more rounded if possible.

Use `border-radius`, you already used it on the `Button`.
> Also, make the elements centered in better way, as well, as the "overreach" on the first button above.

The button is overreaching to the right because the `Container` `width` is set to `40px`, the text does not fit into it. The black background is there because it is set on the `header`, i.e. the button's parent element.
> unify text fonds

Apply `font-family` to `body`.
> make button a little smaller

Reduce its `padding`.

Finally, I'd suggest you take a look at flexbox. It is quite powerful, and easy to learn. I learned it from [A Complete Guide to Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/) and always come back to it for reference. For example, you could apply `display: flex`, `flex-direction: column`, and `align-items: center` to `Container`. This centres the items nicely and you can then remove the `br` tag below the input.

Regarding `styled-components` setup:
- They should be `.ts` files because type checking is useful for them as well when they take props.
- I suggest dropping the `.styled` suffix and renaming the `styles` directory to e.g. `atoms`. This is because you will probably find yourself adding logic into these components and adding styles into others so the division will become muddy. However, keeping generic components like `Button` etc. in a separate directory is a good pattern.

2023-10-06 19:06 UTC, komret commented on src/context.tsx
> +    allHeroes: [
Yes, but let's not worry about it now.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +export const StyledSubeader = styled.h2`
typo

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
The file is called `Header`, but contains various unrelated components. Some of them have the `Styled` prefix, others don't. Clean that up pls.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +  padding: 40px 50;
missing unit

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +  align-text: center;
Did you mean `text-align`? Same issue in `Container`. Make Eslint work pls, it should warn you about this.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +  border-bottom: 2px solid red;
Let's only use theme colours. There are multiple occurrences like this.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +  }
This probably doesn't do anything.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +  left: 10px;
Changing an element's `position` should be the last resort as it can break stuff easily. Do you want to offset it from the left? Use `margin-left` instead.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Header.styled.js
> +`;
Not used, probably better to add these later.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Flex.styled.js
Not used. Do you want me to help you finish it? How should it be used? Otherwise, let's remove it.

2023-10-06 19:06 UTC, komret commented on src/App.tsx
> +const theme = {
This is worth a separate file.

2023-10-06 19:06 UTC, komret commented on src/App.tsx
> +  mobile: "768px",
Should be nested under `breakpoints`.

2023-10-06 19:06 UTC, komret commented on src/components/styles/Container.styled.js
> +  body {
Not applied because `body` is not an ancestor of `Container`.

2023-10-11 13:48 UTC, Vik0411 commented on src/components/styles/Header.styled.js
> +export const StyledSubeader = styled.h2`
correcting

2023-10-11 13:56 UTC, Vik0411 commented on src/components/styles/Header.styled.js
correcting

2023-10-11 14:23 UTC, Vik0411 commented on src/components/styles/Header.styled.js
> +  padding: 40px 50;
correcting. I would be interested what is it actually taking like this. It just cancelling the whole padding style no?

2023-10-11 14:24 UTC, Vik0411 commented on src/components/styles/Header.styled.js
> +  padding: 40px 50;
not needed style actually

2023-10-11 14:24 UTC, Vik0411 commented on src/components/styles/Header.styled.js
> +  align-text: center;
correcting, not needed in the end

2023-10-11 14:25 UTC, Vik0411 commented on src/components/styles/Header.styled.js
> +`;
correcting

2023-10-11 14:25 UTC, Vik0411 commented on src/components/styles/Flex.styled.js
removing for now

2023-10-11 14:33 UTC, Vik0411 commented on src/App.tsx
> +const theme = {
adjusting

2023-10-11 14:33 UTC, Vik0411 commented on src/App.tsx
> +  mobile: "768px",
not understanding this

2023-10-11 14:34 UTC, Vik0411 commented on src/components/styles/Container.styled.js
> +  body {
adjusting

2023-10-11 15:39 UTC, komret commented on src/components/styles/Header.styled.js
> +  padding: 40px 50;
Yes, it makes the property invalid and it does not apply. You can see it in devtools.

2023-10-11 15:48 UTC, komret commented on src/components/styles/Header.styled.js
If you want to keep it like this, `Header` still does not describe the content very well. You can either split it into separate files or rename this one to `typography.ts`.

2023-10-11 15:50 UTC, komret commented on src/App.tsx
> +const theme = {
It shouldn't be in atoms IMO as it is not an atom. I'd move it to `src`.

2023-10-11 15:52 UTC, komret commented on src/App.tsx
> +  mobile: "768px",
To match the structure or `colors`:

```ts
{
  colors: {
    header: "#000000",
    subheader: "#808080",
    body: "#000000",
    footer: "#000000",
  },
  breakpoints: {
    mobile: "768px",
  },
};
```

2023-10-12 08:38 UTC, Vik0411 commented on src/components/styles/Header.styled.js
yes, that s better. wanted to point this out. adjusting

2023-10-12 08:38 UTC, Vik0411 commented on src/App.tsx
> +const theme = {
ok, had it there first, probably true. moving

2023-10-12 08:49 UTC, Vik0411 commented on src/App.tsx
> +  mobile: "768px",
I see, true.

2023-10-12 09:43 UTC, Vik0411 reviewed
more current state of the arts
after rebase
<img width="476" alt="with-colors-change" src="https://github.com/Vik0411/lotr/assets/50553439/ec44698c-1edf-4527-8f11-88ed62364a29">
color changes
<img width="476" alt="after-rebase" src="https://github.com/Vik0411/lotr/assets/50553439/2da2ba90-84f9-4844-9c16-7cf8f65ad562">
flex reversed
<img width="476" alt="reversed" src="https://github.com/Vik0411/lotr/assets/50553439/a035614e-206f-455f-a5fe-48ec14b35d98">

2023-10-12 19:06 UTC, komret commented on src/components/styles/Header.styled.js
It should be `typography` (lowercase) because it is not a name of a component.

2023-10-13 18:02 UTC, komret requested changes
Ad hoc properties like `margin`, which will not be shared by the majority of instances of a component should be set individually for each instance. Example usage:

```ts
import styled from `styled-components';

import {Button} from './atoms/Button`;

const StyledButton = styled(Button)`
 margin-top: 5px;
`;
```

This approach lets you reuse a component many times without needing to create unnecessary copies like `FirstButton`.

See the [docs](https://styled-components.com/docs/basics#extending-styles).

Passing extra props (e.g. `color`) only to affect styles is not a good practice. Less props means more readable and predictable code.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Button.ts
> +  text-align: center;
Redundant. This value is default.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Button.ts
> +  width: 75%;
This sets the width to 75% of the container width. I don't think it makes sense given that you can't tell how wide the container is going to be. We can expect the `Button` to be used in various places in the application. If you want to set some width, lets use some absolute `min-width` instead.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Button.ts
> +  margin-top: 5px;
There will be case when you don't want to have a margin, I would not set this globally.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
I am surprised TypeScript allows a `color` prop, it is certainly not standard. I'd remove this and only allow overridig the CSS property by styling the component ad hoc.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Button.ts
> +  position: absolute;
Why do you want to position this element? It doesn't seem necessary. Also, all other properties are identical to `Button`, you should inherit from it.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Container.ts
> +  position: relative;
Why?

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Container.ts
> +  justify-content: center;
This has no effect.

2023-10-13 18:02 UTC, komret commented on src/themes.ts
> +    firstButton: "#FFFFFF",
Naming doesn't match usage (e.g. `firstButton` used on `Button`, `header` used on `Input`).

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Input.ts
> +  border-radius: 10px 100px / 120px;
👀

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Input.ts
> +  }
1. It doesn't work without `&`
2. It is actually a good thing. Please remove these lines, I don't see any point.

2023-10-13 18:02 UTC, komret commented on src/components/atoms/Input.ts
> +  transition: width 0.4s ease-in-out;
This won't work without absolute values.

2023-11-07 12:37 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  text-align: center;
removed. thx

2023-11-07 12:38 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  width: 75%;
I would leave this as it looks good to me when 75 percent compared to container and first btn

2023-11-07 12:39 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  margin-top: 5px;
moved, thx

2023-11-07 12:39 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
I moved all colors to "adhoc" styles

2023-11-07 12:40 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  position: absolute;
I am not sure now, I believe I had to add this relation to make it look how I wanted, but have to review this why it looks better actually now

2023-11-07 12:41 UTC, Vik0411 commented on src/themes.ts
> +    firstButton: "#FFFFFF",
changed

2023-11-07 12:42 UTC, Vik0411 commented on src/components/atoms/Input.ts
> +  border-radius: 10px 100px / 120px;
I saw that in docs and liked it so I used it. We can leave it no?

2023-11-07 12:42 UTC, Vik0411 commented on src/components/atoms/Input.ts
> +  }
removed

2023-11-07 12:42 UTC, Vik0411 commented on src/components/atoms/Input.ts
> +  transition: width 0.4s ease-in-out;
removed. could you pls just provide one example with absolute values? thx

2023-11-07 12:57 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  width: 75%;
the container has width: 15vw, and let us assume for now that all btns are gonna be only in container. that could pass, no?

2023-11-07 13:09 UTC, Vik0411 commented on src/components/styles/Header.styled.js
adjusting

2023-11-07 13:10 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  position: absolute;
<img width="633" alt="Screenshot 2023-11-07 at 2 08 03 PM" src="https://github.com/Vik0411/lotr/assets/50553439/0c64ed30-cc47-40b2-8b8a-663877ed0934">
<img width="633" alt="Screenshot 2023-11-07 at 2 08 35 PM" src="https://github.com/Vik0411/lotr/assets/50553439/9c51b5fb-b078-402f-85ff-551a960576b3">
 
I think I prefer this look, the way the header lines are shorten as the btn doesnt interfer with the structure

2023-11-07 13:25 UTC, Vik0411 commented
btw I would like to change this input color from blue to other color. I think it is a default, but I could not find an override. Dont you know about this?

<img width="633" alt="Screenshot 2023-11-07 at 1 59 49 PM" src="https://github.com/Vik0411/lotr/assets/50553439/b95b0f63-2563-4b6b-843e-01586b201dab">

2023-11-23 16:44 UTC, Vik0411 commented on src/components/styles/Header.styled.js
not done

2023-11-23 16:48 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  width: 75%;
should be specified on container

2023-11-28 18:27 UTC, komret commented on src/components/styles/Header.styled.js
Not done and the app doesn't compile because of that.
![Screenshot 2023-11-28 at 19 26 48](https://github.com/Vik0411/lotr/assets/42465546/4ed8ab6c-8e8b-4815-affc-44f4b38c357b)

2023-11-28 18:29 UTC, komret commented on src/components/atoms/Button.ts
> +  width: 75%;
Width should be specified on the container so that the button can be reused.

2023-11-28 19:03 UTC, komret commented
> btw I would like to change [this input color](https://github.com/Vik0411/lotr/assets/50553439/b95b0f63-2563-4b6b-843e-01586b201dab) from blue to other color. I think it is a default, but I could not find an override. Dont you know about this?

It is a property set by Chromium browsers by default, you can override the colour in `outline-color` or disable it altogether with `outline: none`.

2023-11-28 19:07 UTC, komret requested changes
Still some improvements to do, but it is starting to look better. You forgot to install `@types/styled-components`.

2023-11-28 19:07 UTC, komret commented on src/components/atoms/Button.ts
> +export const ListSurvivorsBtn = SendToCoffinBtn;
These are not atoms, better move them to the file where they are used. Atoms are general components. Same for `InputFallen`.

2023-11-28 19:07 UTC, komret commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
I can see you moved it, but you keep expecting the `color` prop in the styled components which should not use it at all. You don't pass it to the components anyway. Please remove the `color` prop from `ListAllBtn` and `SendToCoffinBtn`.

2023-11-28 19:07 UTC, komret commented on src/components/atoms/Input.ts
> +  transition: width 0.4s ease-in-out;
First, there was no way for the input to change its width, so the `transition` property was redundant. It is only applied when the specified property (`width`) changes.
Second, when you add some way to change the width, it must be specified as an absolute value, CSS cannot handle transition for a dimension defined as `auto`, which is the default value. Try the following example. Then, change either value for `auto` and the transition will stop working.

```ts
  const [width, setWidth] = useState("100px");
  const toggleWidth = () => setWidth(width === "100px" ? "200px" : "100px");

  return (
    <div>
      <form onSubmit={addFallenHero}>
        <InputFallen
          type="text"
          value={fallenHero}
          placeholder="Input your fallen hero..."
          onChange={handleChange}
          onFocus={toggleWidth}
          onBlur={toggleWidth}
          style={{ width }}
        />
...
```

2023-11-29 11:29 UTC, Vik0411 commented on src/components/styles/Header.styled.js
solved [in this commit](https://github.com/Vik0411/lotr/pull/14/commits/45a4740f6aef18b860fbc31bae87611b97265ff3)

2023-11-29 11:32 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +  width: 75%;
changed to min-width, it is ok that way, changed in [this commit](https://github.com/Vik0411/lotr/pull/14/commits/3ea9ed6fcef99c60011badf9f19da9dd5705ff4d)

2023-11-29 11:34 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
removed also in [this commit](https://github.com/Vik0411/lotr/pull/14/commits/3ea9ed6fcef99c60011badf9f19da9dd5705ff4d)

2023-11-29 11:35 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +export const ListSurvivorsBtn = SendToCoffinBtn;
moved[ in this commit](https://github.com/Vik0411/lotr/pull/14/commits/3ea9ed6fcef99c60011badf9f19da9dd5705ff4d)

2023-11-29 17:17 UTC, komret commented on src/components/atoms/Button.ts
> +  width: 75%;
It is still there... twice 😢 
```ts
color: ${({ color, theme }) => color || theme.colors.basicWhite};
```

2023-11-29 17:18 UTC, komret commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
It is still there... twice 😢 
```ts
color: ${({ color, theme }) => color || theme.colors.basicWhite};
```

2023-11-29 17:20 UTC, komret commented on src/components/atoms/Button.ts
> +export const ListSurvivorsBtn = SendToCoffinBtn;
Give the same treatment to `HeaderListAll` and `SubheaderListAll` please. `HeaderListAll` shouldn't repeat the properties inherited form `Header.

2023-11-29 17:28 UTC, komret commented on src/components/atoms/Button.ts
> +  width: 75%;
You are setting a button's width based on viewport width. I can't see any relation between these two. Moreover, setting `min-width` to 10vw doesn't change the UI in any way so I can't figure out why you want to do that. I would just remove the line...

2023-11-30 09:08 UTC, Vik0411 commented on src/components/atoms/Button.ts
> +    color: ${({ color, theme }) => color || theme.colors.firstButton};
here it should be

2023-12-04 08:26 UTC, merged